#!/bin/bash

while true

do

	echo "Checking and Auto Splitting Komodo UTXO's..."

	sleep 2

	../splitter/kmd.sh
	
	sleep 5


	echo "Checking and Auto Splitting Assetchain UTXO's..."

	sleep 2

	../splitter/assetchains.sh

	sleep 5

	

	echo "Checking and Auto Splitting External Coins UTXO's..."

	sleep 2

	../splitter/coins.sh

	sleep 600

done
